# The default SRS config for the testbed

cu_cp:
  amf:
    addr: 192.168.101.14
    bind_addr: 0.0.0.0
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "99999"
            tai_slice_support_list:
              - sst: 1
                sd: 162
              - sst: 1
                sd: 163
              - sst: 1
                sd: 164
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
                sd: 162
              - sst: 1
                sd: 163
              - sst: 1
                sd: 164
  security:
    nea_pref_list: nea2,nea1,nea3,nea0    # required for iPhone
  mobility:
    cells:
      - nr_cell_id: 0x66C000          # For the default gnb_id=411 (gnb_id_bit_length=22), NR cell IDs start with 0x66C000 and increment for each cell of the DU.
        periodic_report_cfg_id: 1     # This will configure a periodical report config for the serving cell.
    report_configs:                                        # Define report configs for cell 1
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024


cell_cfg:
  dl_arfcn: 630684
  common_scs: 30
  band: 78
  plmn: "00101"
  tac: 1
  pci: 1
  channel_bandwidth_MHz: 40
  ssb:
     ssb_block_power_dbm: -21
  nof_antennas_dl: 4
  nof_antennas_ul: 4
  # tdd_ul_dl_cfg:
  #   nof_dl_symbols: 5
  #   nof_dl_slots: 5
  #   nof_ul_slots: 4
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 7
    nof_dl_symbols: 6
    nof_ul_slots: 2
    nof_ul_symbols: 4
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 12
  pusch:
    mcs_table: qam256

cells:
  - pci: 1
    dl_arfcn: 630684

ru_ofh:
  ru_bandwidth_MHz: 40
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 429
  t1a_min_cp_ul: 285
  t1a_max_up: 196
  t1a_min_up: 50
  ta4_max: 75
  ta4_min: 0
  is_prach_cp_enabled: true
  ignore_ecpri_payload_size: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: none
  compr_bitwidth_prach: 16
  enable_ul_static_compr_hdr: false
  enable_dl_static_compr_hdr: false
  iq_scaling: 2.0
  cells:
  - network_interface: 0000:3f:00.5    # PCI address of the NIC card in your server
    ru_mac_addr: e2:53:8d:8f:a4:6b
    du_mac_addr: aa:bb:cc:11:22:33
    vlan_tag_up: 1
    vlan_tag_cp: 1
    prach_port_id: [4, 5, 6, 7]
    dl_port_id: [0, 1, 2, 3]
    ul_port_id: [0, 1, 2, 3]

# Will be added by the update script
#hal:
#   eal_args: "--lcores (0-1)@(1-30)"

log:
  filename: ./gnb.log
  ofh_level: warning
  all_level: warning
  gtpu_level: warning


metrics:
  autostart_stdout_metrics: true
